### ISSUE TITLE
Need a new release build

### ISSUE THREAD

**Issue by gravly** [tlipinski/bitwig-novation-impulse#14]
Hi Tomasz
thanks so much for the scripting support.  I am not very familiar with Java and I was wondering if you can do a new beta release with the clip launcher changes.

**Comment by gravly** [comment]
I managed to get it built but the clip launcher still isn't working.  beta4 seems to function pretty much exactly as beta 3

**Comment by tlipinski** [comment]
Hi @gravly give me a moment, I'll release beta.4.
I didn't know that anyone uses this script except me;)

**Comment by gravly** [comment]
Your description says the clip launcher is working but I haven't found that to be the case on beta4.

Not so many impulse 25 users on bitwig it seems.  Apparently it is painful to script ffor.  Have played with a few of the JavaScript control scripts for this keyboard but they've all got bugs.  I can't find any ways to get the pads and the keyboard addressing separate instruments on any of the available scripts, including yours.  The bitwig supplied script has some frustrating glitches including second pot doesn't work and nor does the 5th clip launcher.

Anyway I'm happy to play with your script for a while see what different capabilities and issues it has to the others.

Thanks once again for your efforts and for making it available.

**Comment by tlipinski** [comment]
@gravly please check version I've built https://github.com/tlipinski/bitwig-novation-impulse/releases/tag/v1.0-beta.4
Make sure you followed all "Setting template" steps from https://github.com/tlipinski/bitwig-novation-impulse#setting-template
Does it help?

**Comment by gravly** [comment]
Thanks for the quick work.

Yes, to an extent that worked.  It will launch and stop the first clip on the first track with the top left pad button.  Perhaps I'm missing something and I definitely should try some more fiddling but I can't get any other clip launcher buttons to work yet.

**Comment by gravly** [comment]
Yeah, something definitely broken, like a loop through all the pads perhaps, because the light only works on pad1.  I can switch scenes and this changes the color on pad one but none of the other pads light up.  I can't start or stop scene/clip from recording except moving it to pad one using the scene button and then using pad 1.   When I move to a different track, either using the computer or with Shift>Tranpose on the Impulse, pad one still controls the first track rather than the selected track.  The second row of pads doesn't seem to work at all (logically should be the first four slots on the track below the selected track).

**Comment by gravly** [comment]
I am running Linux, in case that matters.

**Comment by gravly** [comment]
...and Bitwig 2.1

**Comment by tlipinski** [comment]
I'm running Linux and Bitwig 2.1 as well so that's not the case.
Could you please switch on Debug mode in controller's settings and tell me what happens when you press each pad?
There should be messages like:
`[0B:xx:127] -> ClipLauncherCommand`
What values "xx" do you see for each pad for top and bottom rows?

**Comment by gravly** [comment]
[B0:61:127] -> ClipLauncherCommand
[B0:61:127] -> ClipLauncherCommand
[B0:62:127] -> ClipLauncherCommand
[B0:63:127] -> ClipLauncherCommand
[B0:64:127] -> ClipLauncherCommand
[B0:65:127] -> ClipLauncherCommand
[B0:66:127] -> ClipLauncherCommand
[B0:67:127] -> ClipLauncherCommand
[B0:60:127] -> ClipLauncherCommand
PlaybackQueued 0 true
PlaybackQueued 0 false
[B1:13:1] -> ShiftPressedCommand
[B0:39:1] -> NoOpShiftCommand
[B0:60:127] -> ClipStopCommand
Playing 0 false
[B1:13:0] -> ShiftReleasedCommand
[B0:39:0] -> NoOpShiftCommand

**Comment by gravly** [comment]
This is starting at pad two and working through to pad 8.  The final one, the 60 is pad 1, the one which is working, and as you can see triggered a clip.
I have clips stored in the second and fourth scene on track one as well, but as you can see they weren't triggered.

I seem to remember a few years ago I put the updated firmware on this keyboard, so not sure if different firmware could effect things.  It is also possible I fiddled with some other settings in the Impulse menus at some stage without knowing what I was doing but shouldn't the Template upload fix that.

**Comment by tlipinski** [comment]
60-67 for pad1-pad8 values are correct, they are the same on my Impulse 49 so this doesn't seem to be an issue.
I wonder about another thing. A while ago I checked Novation 25 script provided by Bitwig and I noticed that clip launcher behaves totally different than Automap connected to Ableton which I used as a guideline.
The thing was that Bitwig's script was like track oriented while Automap was scene oriented. Maybe this makes all the confusion?

This is how it worked in Automap. Let's say we have such clips in Bitwig (X means that there's clip):
```
        | Track 1 | Track 2 | Track 3 | Track 4 | Track 5 | Track 6 |
--------|---------|---------|---------|---------|---------|---------|
Scene 1 |    X    |    X    |         |    X    |         |    X    |
Scene 2 |         |    X    |    X    |    X    |    X    |         |
```
So if Scene 1 is selected then clip launcher lights are:
```
| X | X |   | X |
|   | X |   |   |
```
For Scene 2:
```
|   | X | X | X |
| X | X |   |   |
```
Is this the same way how you expect it to work?
Script provided by Bitwig was showing something completely different. As far as I remember it was more track oriented and clip launcher was showing all clips for single track. Am I right?

**Comment by gravly** [comment]
I wouldn't have expected it that way, not sure if it is better.  I know the Bitwig way and only have limited Ableton experience.

On the bitwig provided script
Top 4 pads were showing the first four scene slots for the selected track.
Pads 5-8 show the first four scene slots for the track below that.

I'm not sure about track grouping with all this, perhaps it makes no difference.  I've only just moved from Bitwig 1.x so grouping isn't something I've played with yet.

**Comment by gravly** [comment]
Perhaps it was behaving as you suggest.  I'll be able to check it this weekend.  The machine got put down for night and I must go too...

**Comment by gravly** [comment]
Yes you're right this is the answer.  I had a quick play before I'm off to work and thinking about it the Abelton way I was able to get the other lights and some of the triggers working.  It was buggy as hell and not really usable but yes the other pads are there after all.  Apologies for the confusion.  I have a feeling it doesn't show scene one me two on each row, just scene one, tracks one to eight.  On the weekend I will have another go and try to tease out the behaviour and a few of the issues and write down the results.

**Comment by gravly** [comment]
OK my apologies for being wrong on most counts.

clip launcher is working fine and it was my bad.  Basically I failed to have all record buttons enabled on tracks 1-8.

I see I have even misunderstood your description of ableton like behaviour.  So what I see is what you have described: the appearance of tracks one to eight on the eight pads, moving when the scene is moved.

In short - it all works.  Sorry I may have put you to trouble bug hunting for non-existent bugs.

I have also found that it doesn't really matter that the pads can't be addressed as a separate device/midi input.  Since the transpose button doesn't effect the pads, the keyboard can just be set to a higher octave (and subsequently downshifted with a note shifter if neccessary), and drum notes can then be filtered out of the keyboard stream with a note filter.  It's a bit of hassle but it does work.

Thanks for your time and energy once again.

**Comment by tlipinski** [comment]
You really don't need to feel sorry about anything. Resolving such issues is just maintainer's job. This one is still valid because it exposed missing documentation which caused confusion. Please feel free to report anything you find. Thanks!
