### ISSUE TITLE
Conflict getting the driver to co-exist with Moss's Midi Monitor

### ISSUE THREAD

**Issue by carlca** [tlipinski/bitwig-novation-impulse#16]
I am trying to configure Moss's Midi Monitor, but when I try to select the Impulse as my chosen MIDI source, I get this error:

![Screenshot 2020-10-31 at 16 24 15](https://user-images.githubusercontent.com/260612/97790206-9277e800-1bbe-11eb-8f48-93adec6b3ea7.png)

If I disable your device script, I can activate the Midi Monitor, but obviously I would like both to be working side by side. Interestingly, the keyboard is still sending MIDI, even with your script disabled, but presumably with a reduced feature set.

I asked Jürgen about this issue, and he suggested that your script may not be "multi-client".
Your thoughts? 🙂

**Comment by git-moss** [comment]
Sorry, but you misunderstood me. The driver is not multi-client. A driver is the low-level software which is the bridge between the hardware (impulse in this case) and the operating system. There is nothing that can be done to fix this on a script level.

**Comment by carlca** [comment]
Sorry for my misunderstanding, and thanks for following up 😉
