### ISSUE TITLE
Sustain pedal support

### ISSUE THREAD

**Issue by ryanrod** [tlipinski/bitwig-novation-impulse#17]
Bitwig Studio 4.0.1
Novation Impulse 61
Windows 10

Using this controller script, sustain pedal events (cc64) on the Impulse 61 are not processed correctly.
Controller script console output:

```
[B2:64:127] -> unhandled
[B2:64:0] -> unhandled
```

Would be happy to submit a PR for a fix for this with a little bit of guidance. I assume there's just some sort of mapping missing?

**Comment by tlipinski** [comment]
Hi @ryanrod I believe that handling sustain pedal should be as simple as adding mapping in this method in a similar way to mod wheel
https://github.com/tlipinski/bitwig-novation-impulse/blob/152bd38249af4c755ba50c745cf420ce4d6e366a/src/main/java/net/tlipinski/bitwig/controller/NovationImpulseExtension.java#L105

```
  String sustainPedal = "B264??";
```
and passing this value to `host.getMidiInPort(index).createNoteInput(......)`

I no longer own Impulse so I'm unable to test it properly but anyway I hope it will help. Please submit PR if it works:)

**Comment by tlipinski** [comment]
@ryanrod I'm sorry it took so long, but finally sustain pedal is supported in most recent v1.0 version

**Comment by ryanrod** [comment]
Thanks for fixing this! It works great.
